apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent
  namespace: bookrent
  labels:
    app: rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent
  template:
    metadata:
      labels:
        app: rent
    spec:
      containers:
        - name: rent
          image: bookrentskccacr.azurecr.io/rent:v1.1
          ports:
            - containerPort: 8080
          env:
            - name: book-url
              valueFrom:
                configMapKeyRef:
                  name: book-cm
                  key: url
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 250m
          #readinessProbe:
          #  httpGet:
          #    path: '/rents'
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/rents'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5