apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: bookrent
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: bookrentskccacr.azurecr.io/book:v1.4
          ports:
            - containerPort: 8080
          #readinessProbe:
          #  httpGet:
          #    path: '/actuator/health'
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 10
          #livenessProbe:
          #  httpGet:
          #    path: '/actuator/health'
          #    port: 8080
          #  initialDelaySeconds: 120
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 5